apiVersion: v1
kind: Pod
metadata:
  name: epc
  labels:
    app: epc
spec:
  containers:
  - name: open5gs
    image: snslab/open5gs:latest
    env:
    - name: MCC
      value: "222"
    - name: MNC
      value: "93"
    - name: TAC
      value: "7"
    securityContext:
      privileged: true
  - name: open5gs-webui
    image: snslab/open5gs-webui:latest
  - name: mongodb
    image: mongo
  - name: mongo-express
    image: mongo-express
    env:
    - name: ME_CONFIG_MONGODB_SERVER
      value: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: epc-mongo-express-service
spec:
  selector:
    app: epc
  type: NodePort
  ports:
  - name: web-ui
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: epc-open5gs-webui-service
spec:
  selector:
    app: epc
  type: NodePort
  ports:
  - name: web-ui
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: epc-service
spec:
  selector:
    app: epc
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: srsenb
  labels:
    app: srsenb
spec:
  containers:
  - name: srsenb
    image: snslab/srsenb:latest
    env:
    - name: empower_pod_addr
      value: 127.0.0.1
    - name: mcc
      value: "222"
    - name: mnc
      value: "93"
    - name: n_prb
      value: "50"
    securityContext:
      privileged: true
